// Code generated by the cross-service DTO refactor; DO NOT EDIT by hand.
//
// These structs mirror the generated query result/model types of OTHER
// services. The owning service generates them from its own queries; consuming
// services build them from gRPC responses and must keep this file in sync with
// the owner's generated types.
package dto

import (
	"time"
)

type GetUserByIDRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}
