// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: stats/stats.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoryStatsService_FindMonthPrice_FullMethodName         = "/pb.CategoryStatsService/FindMonthPrice"
	CategoryStatsService_FindYearPrice_FullMethodName          = "/pb.CategoryStatsService/FindYearPrice"
	CategoryStatsService_FindMonthlyTotalPrices_FullMethodName = "/pb.CategoryStatsService/FindMonthlyTotalPrices"
	CategoryStatsService_FindYearlyTotalPrices_FullMethodName  = "/pb.CategoryStatsService/FindYearlyTotalPrices"
)

// CategoryStatsServiceClient is the client API for CategoryStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsServiceClient interface {
	FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
}

type categoryStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsServiceClient(cc grpc.ClientConnInterface) CategoryStatsServiceClient {
	return &categoryStatsServiceClient{cc}
}

func (c *categoryStatsServiceClient) FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsServiceServer is the server API for CategoryStatsService service.
// All implementations must embed UnimplementedCategoryStatsServiceServer
// for forward compatibility.
type CategoryStatsServiceServer interface {
	FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error)
	FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error)
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

// UnimplementedCategoryStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsServiceServer struct{}

func (UnimplementedCategoryStatsServiceServer) FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) mustEmbedUnimplementedCategoryStatsServiceServer() {}
func (UnimplementedCategoryStatsServiceServer) testEmbeddedByValue()                              {}

// UnsafeCategoryStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsServiceServer interface {
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

func RegisterCategoryStatsServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCategoryStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsService_ServiceDesc, srv)
}

func _CategoryStatsService_FindMonthPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, req.(*FindYearMonthTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, req.(*FindYearTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoryStatsService",
	HandlerType: (*CategoryStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthPrice",
			Handler:    _CategoryStatsService_FindMonthPrice_Handler,
		},
		{
			MethodName: "FindYearPrice",
			Handler:    _CategoryStatsService_FindYearPrice_Handler,
		},
		{
			MethodName: "FindMonthlyTotalPrices",
			Handler:    _CategoryStatsService_FindMonthlyTotalPrices_Handler,
		},
		{
			MethodName: "FindYearlyTotalPrices",
			Handler:    _CategoryStatsService_FindYearlyTotalPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}

const (
	CategoryStatsByIdService_FindMonthPriceById_FullMethodName         = "/pb.CategoryStatsByIdService/FindMonthPriceById"
	CategoryStatsByIdService_FindYearPriceById_FullMethodName          = "/pb.CategoryStatsByIdService/FindYearPriceById"
	CategoryStatsByIdService_FindMonthlyTotalPricesById_FullMethodName = "/pb.CategoryStatsByIdService/FindMonthlyTotalPricesById"
	CategoryStatsByIdService_FindYearlyTotalPricesById_FullMethodName  = "/pb.CategoryStatsByIdService/FindYearlyTotalPricesById"
)

// CategoryStatsByIdServiceClient is the client API for CategoryStatsByIdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsByIdServiceClient interface {
	FindMonthPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindMonthlyTotalPricesById(ctx context.Context, in *FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(ctx context.Context, in *FindYearTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
}

type categoryStatsByIdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsByIdServiceClient(cc grpc.ClientConnInterface) CategoryStatsByIdServiceClient {
	return &categoryStatsByIdServiceClient{cc}
}

func (c *categoryStatsByIdServiceClient) FindMonthPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindMonthPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByIdServiceClient) FindYearPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindYearPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByIdServiceClient) FindMonthlyTotalPricesById(ctx context.Context, in *FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindMonthlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByIdServiceClient) FindYearlyTotalPricesById(ctx context.Context, in *FindYearTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByIdService_FindYearlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsByIdServiceServer is the server API for CategoryStatsByIdService service.
// All implementations must embed UnimplementedCategoryStatsByIdServiceServer
// for forward compatibility.
type CategoryStatsByIdServiceServer interface {
	FindMonthPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryYearPrice, error)
	FindMonthlyTotalPricesById(context.Context, *FindYearMonthTotalPriceById) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(context.Context, *FindYearTotalPriceById) (*ApiResponseCategoryYearlyTotalPrice, error)
	mustEmbedUnimplementedCategoryStatsByIdServiceServer()
}

// UnimplementedCategoryStatsByIdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsByIdServiceServer struct{}

func (UnimplementedCategoryStatsByIdServiceServer) FindMonthPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthPriceById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) FindYearPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearPriceById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) FindMonthlyTotalPricesById(context.Context, *FindYearMonthTotalPriceById) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalPricesById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) FindYearlyTotalPricesById(context.Context, *FindYearTotalPriceById) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalPricesById not implemented")
}
func (UnimplementedCategoryStatsByIdServiceServer) mustEmbedUnimplementedCategoryStatsByIdServiceServer() {
}
func (UnimplementedCategoryStatsByIdServiceServer) testEmbeddedByValue() {}

// UnsafeCategoryStatsByIdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsByIdServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsByIdServiceServer interface {
	mustEmbedUnimplementedCategoryStatsByIdServiceServer()
}

func RegisterCategoryStatsByIdServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsByIdServiceServer) {
	// If the following call pancis, it indicates UnimplementedCategoryStatsByIdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsByIdService_ServiceDesc, srv)
}

func _CategoryStatsByIdService_FindMonthPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindMonthPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindMonthPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindMonthPriceById(ctx, req.(*FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByIdService_FindYearPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindYearPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindYearPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindYearPriceById(ctx, req.(*FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByIdService_FindMonthlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindMonthlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindMonthlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindMonthlyTotalPricesById(ctx, req.(*FindYearMonthTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByIdService_FindYearlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByIdServiceServer).FindYearlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByIdService_FindYearlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByIdServiceServer).FindYearlyTotalPricesById(ctx, req.(*FindYearTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsByIdService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsByIdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsByIdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoryStatsByIdService",
	HandlerType: (*CategoryStatsByIdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthPriceById",
			Handler:    _CategoryStatsByIdService_FindMonthPriceById_Handler,
		},
		{
			MethodName: "FindYearPriceById",
			Handler:    _CategoryStatsByIdService_FindYearPriceById_Handler,
		},
		{
			MethodName: "FindMonthlyTotalPricesById",
			Handler:    _CategoryStatsByIdService_FindMonthlyTotalPricesById_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesById",
			Handler:    _CategoryStatsByIdService_FindYearlyTotalPricesById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}

const (
	CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName         = "/pb.CategoryStatsByMerchantService/FindMonthPriceByMerchant"
	CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName          = "/pb.CategoryStatsByMerchantService/FindYearPriceByMerchant"
	CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName = "/pb.CategoryStatsByMerchantService/FindMonthlyTotalPricesByMerchant"
	CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName  = "/pb.CategoryStatsByMerchantService/FindYearlyTotalPricesByMerchant"
)

// CategoryStatsByMerchantServiceClient is the client API for CategoryStatsByMerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsByMerchantServiceClient interface {
	FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
}

type categoryStatsByMerchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsByMerchantServiceClient(cc grpc.ClientConnInterface) CategoryStatsByMerchantServiceClient {
	return &categoryStatsByMerchantServiceClient{cc}
}

func (c *categoryStatsByMerchantServiceClient) FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsByMerchantServiceServer is the server API for CategoryStatsByMerchantService service.
// All implementations must embed UnimplementedCategoryStatsByMerchantServiceServer
// for forward compatibility.
type CategoryStatsByMerchantServiceServer interface {
	FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error)
	FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error)
	mustEmbedUnimplementedCategoryStatsByMerchantServiceServer()
}

// UnimplementedCategoryStatsByMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsByMerchantServiceServer struct{}

func (UnimplementedCategoryStatsByMerchantServiceServer) FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) mustEmbedUnimplementedCategoryStatsByMerchantServiceServer() {
}
func (UnimplementedCategoryStatsByMerchantServiceServer) testEmbeddedByValue() {}

// UnsafeCategoryStatsByMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsByMerchantServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsByMerchantServiceServer interface {
	mustEmbedUnimplementedCategoryStatsByMerchantServiceServer()
}

func RegisterCategoryStatsByMerchantServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsByMerchantServiceServer) {
	// If the following call pancis, it indicates UnimplementedCategoryStatsByMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsByMerchantService_ServiceDesc, srv)
}

func _CategoryStatsByMerchantService_FindMonthPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindYearPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthlyTotalPricesByMerchant(ctx, req.(*FindYearMonthTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearlyTotalPricesByMerchant(ctx, req.(*FindYearTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsByMerchantService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsByMerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsByMerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoryStatsByMerchantService",
	HandlerType: (*CategoryStatsByMerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthPriceByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindMonthPriceByMerchant_Handler,
		},
		{
			MethodName: "FindYearPriceByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindYearPriceByMerchant_Handler,
		},
		{
			MethodName: "FindMonthlyTotalPricesByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}

const (
	OrderStatsService_FindMonthlyTotalRevenue_FullMethodName           = "/pb.OrderStatsService/FindMonthlyTotalRevenue"
	OrderStatsService_FindYearlyTotalRevenue_FullMethodName            = "/pb.OrderStatsService/FindYearlyTotalRevenue"
	OrderStatsService_FindMonthlyTotalRevenueByMerchant_FullMethodName = "/pb.OrderStatsService/FindMonthlyTotalRevenueByMerchant"
	OrderStatsService_FindYearlyTotalRevenueByMerchant_FullMethodName  = "/pb.OrderStatsService/FindYearlyTotalRevenueByMerchant"
	OrderStatsService_FindMonthlyRevenue_FullMethodName                = "/pb.OrderStatsService/FindMonthlyRevenue"
	OrderStatsService_FindYearlyRevenue_FullMethodName                 = "/pb.OrderStatsService/FindYearlyRevenue"
	OrderStatsService_FindMonthlyRevenueByMerchant_FullMethodName      = "/pb.OrderStatsService/FindMonthlyRevenueByMerchant"
	OrderStatsService_FindYearlyRevenueByMerchant_FullMethodName       = "/pb.OrderStatsService/FindYearlyRevenueByMerchant"
)

// OrderStatsServiceClient is the client API for OrderStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatsServiceClient interface {
	FindMonthlyTotalRevenue(ctx context.Context, in *FindYearMonthTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenue(ctx context.Context, in *FindYearTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(ctx context.Context, in *FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error)
	FindMonthlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error)
}

type orderStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatsServiceClient(cc grpc.ClientConnInterface) OrderStatsServiceClient {
	return &orderStatsServiceClient{cc}
}

func (c *orderStatsServiceClient) FindMonthlyTotalRevenue(ctx context.Context, in *FindYearMonthTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindMonthlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindYearlyTotalRevenue(ctx context.Context, in *FindYearTotalRevenue, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindYearlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindMonthlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindYearlyTotalRevenueByMerchant(ctx context.Context, in *FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindYearlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindMonthlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthly)
	err := c.cc.Invoke(ctx, OrderStatsService_FindMonthlyRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindYearlyRevenue(ctx context.Context, in *FindYearOrder, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearly)
	err := c.cc.Invoke(ctx, OrderStatsService_FindYearlyRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindMonthlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthly)
	err := c.cc.Invoke(ctx, OrderStatsService_FindMonthlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindYearlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearly)
	err := c.cc.Invoke(ctx, OrderStatsService_FindYearlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatsServiceServer is the server API for OrderStatsService service.
// All implementations must embed UnimplementedOrderStatsServiceServer
// for forward compatibility.
type OrderStatsServiceServer interface {
	FindMonthlyTotalRevenue(context.Context, *FindYearMonthTotalRevenue) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenue(context.Context, *FindYearTotalRevenue) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyTotalRevenueByMerchant(context.Context, *FindYearMonthTotalRevenueByMerchant) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(context.Context, *FindYearTotalRevenueByMerchant) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderYearly, error)
	FindMonthlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderYearly, error)
	mustEmbedUnimplementedOrderStatsServiceServer()
}

// UnimplementedOrderStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStatsServiceServer struct{}

func (UnimplementedOrderStatsServiceServer) FindMonthlyTotalRevenue(context.Context, *FindYearMonthTotalRevenue) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindYearlyTotalRevenue(context.Context, *FindYearTotalRevenue) (*ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindMonthlyTotalRevenueByMerchant(context.Context, *FindYearMonthTotalRevenueByMerchant) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindYearlyTotalRevenueByMerchant(context.Context, *FindYearTotalRevenueByMerchant) (*ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindMonthlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderMonthly, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindYearlyRevenue(context.Context, *FindYearOrder) (*ApiResponseOrderYearly, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindMonthlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderMonthly, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindYearlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderYearly, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsServiceServer) mustEmbedUnimplementedOrderStatsServiceServer() {}
func (UnimplementedOrderStatsServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatsServiceServer will
// result in compilation errors.
type UnsafeOrderStatsServiceServer interface {
	mustEmbedUnimplementedOrderStatsServiceServer()
}

func RegisterOrderStatsServiceServer(s grpc.ServiceRegistrar, srv OrderStatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStatsService_ServiceDesc, srv)
}

func _OrderStatsService_FindMonthlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalRevenue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindMonthlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenue(ctx, req.(*FindYearMonthTotalRevenue))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindYearlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalRevenue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindYearlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenue(ctx, req.(*FindYearTotalRevenue))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindMonthlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindMonthlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, req.(*FindYearMonthTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindYearlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindYearlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenueByMerchant(ctx, req.(*FindYearTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindMonthlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindMonthlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindMonthlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindMonthlyRevenue(ctx, req.(*FindYearOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindYearlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindYearlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindYearlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindYearlyRevenue(ctx, req.(*FindYearOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindMonthlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindMonthlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindMonthlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindMonthlyRevenueByMerchant(ctx, req.(*FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindYearlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindYearlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindYearlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindYearlyRevenueByMerchant(ctx, req.(*FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatsService_ServiceDesc is the grpc.ServiceDesc for OrderStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderStatsService",
	HandlerType: (*OrderStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalRevenue",
			Handler:    _OrderStatsService_FindMonthlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenue",
			Handler:    _OrderStatsService_FindYearlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindMonthlyTotalRevenueByMerchant",
			Handler:    _OrderStatsService_FindMonthlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenueByMerchant",
			Handler:    _OrderStatsService_FindYearlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindMonthlyRevenue",
			Handler:    _OrderStatsService_FindMonthlyRevenue_Handler,
		},
		{
			MethodName: "FindYearlyRevenue",
			Handler:    _OrderStatsService_FindYearlyRevenue_Handler,
		},
		{
			MethodName: "FindMonthlyRevenueByMerchant",
			Handler:    _OrderStatsService_FindMonthlyRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyRevenueByMerchant",
			Handler:    _OrderStatsService_FindYearlyRevenueByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}

const (
	TransactionStatsService_GetMonthlyAmountSuccess_FullMethodName            = "/pb.TransactionStatsService/GetMonthlyAmountSuccess"
	TransactionStatsService_GetYearlyAmountSuccess_FullMethodName             = "/pb.TransactionStatsService/GetYearlyAmountSuccess"
	TransactionStatsService_GetMonthlyAmountFailed_FullMethodName             = "/pb.TransactionStatsService/GetMonthlyAmountFailed"
	TransactionStatsService_GetYearlyAmountFailed_FullMethodName              = "/pb.TransactionStatsService/GetYearlyAmountFailed"
	TransactionStatsService_GetMonthlyTransactionMethodSuccess_FullMethodName = "/pb.TransactionStatsService/GetMonthlyTransactionMethodSuccess"
	TransactionStatsService_GetYearlyTransactionMethodSuccess_FullMethodName  = "/pb.TransactionStatsService/GetYearlyTransactionMethodSuccess"
	TransactionStatsService_GetMonthlyTransactionMethodFailed_FullMethodName  = "/pb.TransactionStatsService/GetMonthlyTransactionMethodFailed"
	TransactionStatsService_GetYearlyTransactionMethodFailed_FullMethodName   = "/pb.TransactionStatsService/GetYearlyTransactionMethodFailed"
)

// TransactionStatsServiceClient is the client API for TransactionStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionStatsServiceClient interface {
	GetMonthlyAmountSuccess(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error)
	GetYearlyAmountSuccess(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error)
	GetMonthlyAmountFailed(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error)
	GetYearlyAmountFailed(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error)
	GetMonthlyTransactionMethodSuccess(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodSuccess(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
	GetMonthlyTransactionMethodFailed(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodFailed(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
}

type transactionStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionStatsServiceClient(cc grpc.ClientConnInterface) TransactionStatsServiceClient {
	return &transactionStatsServiceClient{cc}
}

func (c *transactionStatsServiceClient) GetMonthlyAmountSuccess(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyAmountSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyAmountSuccess(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyAmountSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetMonthlyAmountFailed(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyAmountFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyAmountFailed(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyAmountFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetMonthlyTransactionMethodSuccess(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyTransactionMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyTransactionMethodSuccess(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyTransactionMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetMonthlyTransactionMethodFailed(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyTransactionMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyTransactionMethodFailed(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyTransactionMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionStatsServiceServer is the server API for TransactionStatsService service.
// All implementations must embed UnimplementedTransactionStatsServiceServer
// for forward compatibility.
type TransactionStatsServiceServer interface {
	GetMonthlyAmountSuccess(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountSuccess, error)
	GetYearlyAmountSuccess(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountSuccess, error)
	GetMonthlyAmountFailed(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountFailed, error)
	GetYearlyAmountFailed(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountFailed, error)
	GetMonthlyTransactionMethodSuccess(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodSuccess(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error)
	GetMonthlyTransactionMethodFailed(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodFailed(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error)
	mustEmbedUnimplementedTransactionStatsServiceServer()
}

// UnimplementedTransactionStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionStatsServiceServer struct{}

func (UnimplementedTransactionStatsServiceServer) GetMonthlyAmountSuccess(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyAmountSuccess(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetMonthlyAmountFailed(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyAmountFailed(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetMonthlyTransactionMethodSuccess(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyTransactionMethodSuccess(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetMonthlyTransactionMethodFailed(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyTransactionMethodFailed(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) mustEmbedUnimplementedTransactionStatsServiceServer() {
}
func (UnimplementedTransactionStatsServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionStatsServiceServer will
// result in compilation errors.
type UnsafeTransactionStatsServiceServer interface {
	mustEmbedUnimplementedTransactionStatsServiceServer()
}

func RegisterTransactionStatsServiceServer(s grpc.ServiceRegistrar, srv TransactionStatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionStatsService_ServiceDesc, srv)
}

func _TransactionStatsService_GetMonthlyAmountSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyAmountSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountSuccess(ctx, req.(*MonthAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyAmountSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyAmountSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountSuccess(ctx, req.(*YearAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetMonthlyAmountFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyAmountFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountFailed(ctx, req.(*MonthAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyAmountFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyAmountFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountFailed(ctx, req.(*YearAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetMonthlyTransactionMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyTransactionMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodSuccess(ctx, req.(*MonthMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyTransactionMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyTransactionMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodSuccess(ctx, req.(*YearMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetMonthlyTransactionMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyTransactionMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodFailed(ctx, req.(*MonthMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyTransactionMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyTransactionMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodFailed(ctx, req.(*YearMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionStatsService_ServiceDesc is the grpc.ServiceDesc for TransactionStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionStatsService",
	HandlerType: (*TransactionStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthlyAmountSuccess",
			Handler:    _TransactionStatsService_GetMonthlyAmountSuccess_Handler,
		},
		{
			MethodName: "GetYearlyAmountSuccess",
			Handler:    _TransactionStatsService_GetYearlyAmountSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyAmountFailed",
			Handler:    _TransactionStatsService_GetMonthlyAmountFailed_Handler,
		},
		{
			MethodName: "GetYearlyAmountFailed",
			Handler:    _TransactionStatsService_GetYearlyAmountFailed_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodSuccess",
			Handler:    _TransactionStatsService_GetMonthlyTransactionMethodSuccess_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodSuccess",
			Handler:    _TransactionStatsService_GetYearlyTransactionMethodSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodFailed",
			Handler:    _TransactionStatsService_GetMonthlyTransactionMethodFailed_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodFailed",
			Handler:    _TransactionStatsService_GetYearlyTransactionMethodFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}

const (
	TransactionStatsByMerchantService_GetMonthlyAmountSuccessByMerchant_FullMethodName            = "/pb.TransactionStatsByMerchantService/GetMonthlyAmountSuccessByMerchant"
	TransactionStatsByMerchantService_GetYearlyAmountSuccessByMerchant_FullMethodName             = "/pb.TransactionStatsByMerchantService/GetYearlyAmountSuccessByMerchant"
	TransactionStatsByMerchantService_GetMonthlyAmountFailedByMerchant_FullMethodName             = "/pb.TransactionStatsByMerchantService/GetMonthlyAmountFailedByMerchant"
	TransactionStatsByMerchantService_GetYearlyAmountFailedByMerchant_FullMethodName              = "/pb.TransactionStatsByMerchantService/GetYearlyAmountFailedByMerchant"
	TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantSuccess_FullMethodName = "/pb.TransactionStatsByMerchantService/GetMonthlyTransactionMethodByMerchantSuccess"
	TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantSuccess_FullMethodName  = "/pb.TransactionStatsByMerchantService/GetYearlyTransactionMethodByMerchantSuccess"
	TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantFailed_FullMethodName  = "/pb.TransactionStatsByMerchantService/GetMonthlyTransactionMethodByMerchantFailed"
	TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantFailed_FullMethodName   = "/pb.TransactionStatsByMerchantService/GetYearlyTransactionMethodByMerchantFailed"
)

// TransactionStatsByMerchantServiceClient is the client API for TransactionStatsByMerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionStatsByMerchantServiceClient interface {
	GetMonthlyAmountSuccessByMerchant(ctx context.Context, in *MonthAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error)
	GetYearlyAmountSuccessByMerchant(ctx context.Context, in *YearAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error)
	GetMonthlyAmountFailedByMerchant(ctx context.Context, in *MonthAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error)
	GetYearlyAmountFailedByMerchant(ctx context.Context, in *YearAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error)
	GetMonthlyTransactionMethodByMerchantSuccess(ctx context.Context, in *MonthMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodByMerchantSuccess(ctx context.Context, in *YearMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
	GetMonthlyTransactionMethodByMerchantFailed(ctx context.Context, in *MonthMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodByMerchantFailed(ctx context.Context, in *YearMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
}

type transactionStatsByMerchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionStatsByMerchantServiceClient(cc grpc.ClientConnInterface) TransactionStatsByMerchantServiceClient {
	return &transactionStatsByMerchantServiceClient{cc}
}

func (c *transactionStatsByMerchantServiceClient) GetMonthlyAmountSuccessByMerchant(ctx context.Context, in *MonthAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetMonthlyAmountSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsByMerchantServiceClient) GetYearlyAmountSuccessByMerchant(ctx context.Context, in *YearAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetYearlyAmountSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsByMerchantServiceClient) GetMonthlyAmountFailedByMerchant(ctx context.Context, in *MonthAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetMonthlyAmountFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsByMerchantServiceClient) GetYearlyAmountFailedByMerchant(ctx context.Context, in *YearAmountTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetYearlyAmountFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsByMerchantServiceClient) GetMonthlyTransactionMethodByMerchantSuccess(ctx context.Context, in *MonthMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsByMerchantServiceClient) GetYearlyTransactionMethodByMerchantSuccess(ctx context.Context, in *YearMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsByMerchantServiceClient) GetMonthlyTransactionMethodByMerchantFailed(ctx context.Context, in *MonthMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsByMerchantServiceClient) GetYearlyTransactionMethodByMerchantFailed(ctx context.Context, in *YearMethodTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionStatsByMerchantServiceServer is the server API for TransactionStatsByMerchantService service.
// All implementations must embed UnimplementedTransactionStatsByMerchantServiceServer
// for forward compatibility.
type TransactionStatsByMerchantServiceServer interface {
	GetMonthlyAmountSuccessByMerchant(context.Context, *MonthAmountTransactionMerchantRequest) (*ApiResponseTransactionMonthAmountSuccess, error)
	GetYearlyAmountSuccessByMerchant(context.Context, *YearAmountTransactionMerchantRequest) (*ApiResponseTransactionYearAmountSuccess, error)
	GetMonthlyAmountFailedByMerchant(context.Context, *MonthAmountTransactionMerchantRequest) (*ApiResponseTransactionMonthAmountFailed, error)
	GetYearlyAmountFailedByMerchant(context.Context, *YearAmountTransactionMerchantRequest) (*ApiResponseTransactionYearAmountFailed, error)
	GetMonthlyTransactionMethodByMerchantSuccess(context.Context, *MonthMethodTransactionMerchantRequest) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodByMerchantSuccess(context.Context, *YearMethodTransactionMerchantRequest) (*ApiResponseTransactionYearPaymentmethod, error)
	GetMonthlyTransactionMethodByMerchantFailed(context.Context, *MonthMethodTransactionMerchantRequest) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodByMerchantFailed(context.Context, *YearMethodTransactionMerchantRequest) (*ApiResponseTransactionYearPaymentmethod, error)
	mustEmbedUnimplementedTransactionStatsByMerchantServiceServer()
}

// UnimplementedTransactionStatsByMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionStatsByMerchantServiceServer struct{}

func (UnimplementedTransactionStatsByMerchantServiceServer) GetMonthlyAmountSuccessByMerchant(context.Context, *MonthAmountTransactionMerchantRequest) (*ApiResponseTransactionMonthAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountSuccessByMerchant not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) GetYearlyAmountSuccessByMerchant(context.Context, *YearAmountTransactionMerchantRequest) (*ApiResponseTransactionYearAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountSuccessByMerchant not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) GetMonthlyAmountFailedByMerchant(context.Context, *MonthAmountTransactionMerchantRequest) (*ApiResponseTransactionMonthAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountFailedByMerchant not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) GetYearlyAmountFailedByMerchant(context.Context, *YearAmountTransactionMerchantRequest) (*ApiResponseTransactionYearAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountFailedByMerchant not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) GetMonthlyTransactionMethodByMerchantSuccess(context.Context, *MonthMethodTransactionMerchantRequest) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodByMerchantSuccess not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) GetYearlyTransactionMethodByMerchantSuccess(context.Context, *YearMethodTransactionMerchantRequest) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodByMerchantSuccess not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) GetMonthlyTransactionMethodByMerchantFailed(context.Context, *MonthMethodTransactionMerchantRequest) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodByMerchantFailed not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) GetYearlyTransactionMethodByMerchantFailed(context.Context, *YearMethodTransactionMerchantRequest) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodByMerchantFailed not implemented")
}
func (UnimplementedTransactionStatsByMerchantServiceServer) mustEmbedUnimplementedTransactionStatsByMerchantServiceServer() {
}
func (UnimplementedTransactionStatsByMerchantServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionStatsByMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionStatsByMerchantServiceServer will
// result in compilation errors.
type UnsafeTransactionStatsByMerchantServiceServer interface {
	mustEmbedUnimplementedTransactionStatsByMerchantServiceServer()
}

func RegisterTransactionStatsByMerchantServiceServer(s grpc.ServiceRegistrar, srv TransactionStatsByMerchantServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionStatsByMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionStatsByMerchantService_ServiceDesc, srv)
}

func _TransactionStatsByMerchantService_GetMonthlyAmountSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthAmountTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyAmountSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetMonthlyAmountSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyAmountSuccessByMerchant(ctx, req.(*MonthAmountTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsByMerchantService_GetYearlyAmountSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearAmountTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyAmountSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetYearlyAmountSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyAmountSuccessByMerchant(ctx, req.(*YearAmountTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsByMerchantService_GetMonthlyAmountFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthAmountTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyAmountFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetMonthlyAmountFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyAmountFailedByMerchant(ctx, req.(*MonthAmountTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsByMerchantService_GetYearlyAmountFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearAmountTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyAmountFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetYearlyAmountFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyAmountFailedByMerchant(ctx, req.(*YearAmountTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthMethodTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyTransactionMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyTransactionMethodByMerchantSuccess(ctx, req.(*MonthMethodTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearMethodTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyTransactionMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyTransactionMethodByMerchantSuccess(ctx, req.(*YearMethodTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthMethodTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyTransactionMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetMonthlyTransactionMethodByMerchantFailed(ctx, req.(*MonthMethodTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearMethodTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyTransactionMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsByMerchantServiceServer).GetYearlyTransactionMethodByMerchantFailed(ctx, req.(*YearMethodTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionStatsByMerchantService_ServiceDesc is the grpc.ServiceDesc for TransactionStatsByMerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionStatsByMerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionStatsByMerchantService",
	HandlerType: (*TransactionStatsByMerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthlyAmountSuccessByMerchant",
			Handler:    _TransactionStatsByMerchantService_GetMonthlyAmountSuccessByMerchant_Handler,
		},
		{
			MethodName: "GetYearlyAmountSuccessByMerchant",
			Handler:    _TransactionStatsByMerchantService_GetYearlyAmountSuccessByMerchant_Handler,
		},
		{
			MethodName: "GetMonthlyAmountFailedByMerchant",
			Handler:    _TransactionStatsByMerchantService_GetMonthlyAmountFailedByMerchant_Handler,
		},
		{
			MethodName: "GetYearlyAmountFailedByMerchant",
			Handler:    _TransactionStatsByMerchantService_GetYearlyAmountFailedByMerchant_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodByMerchantSuccess",
			Handler:    _TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodByMerchantSuccess",
			Handler:    _TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodByMerchantFailed",
			Handler:    _TransactionStatsByMerchantService_GetMonthlyTransactionMethodByMerchantFailed_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodByMerchantFailed",
			Handler:    _TransactionStatsByMerchantService_GetYearlyTransactionMethodByMerchantFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}
